### ISSUE TITLE
User Personas? Why do we need them? How to create them?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/process-handbook#115]
_Every_ project needs a Persona to help the people on the team (_working on **making** the product_) to contextualise, empathise and _focus_ on the needs/goals/pains of the **person _using_** the product/service.

The general format is:
+ Name + Picture
+ Details
+ Goal

![image](https://user-images.githubusercontent.com/194400/45924457-83f77680-bef8-11e8-93c8-58815db30ccd.png)

Though I quite like the addition/inclusion of "***Pain Points***" e.g:
![image](https://user-images.githubusercontent.com/194400/45924465-b7d29c00-bef8-11e8-94f6-222a66d4db02.png)
via: https://www.uxpin.com/studio/blog/ux-designers-5-minute-guide-lean-personas

I would _especially_ like to see the inclusion of a _quantifiable_ pain point e.g: using a scale:
![image](https://user-images.githubusercontent.com/194400/45924741-3f230e00-beff-11e8-8d6d-c97f5ca8a11f.png)
via: https://www.wordstream.com/blog/ws/2018/02/28/pain-points

> There is a _mention_ of Personas in https://github.com/dwyl/product-owner-guide
but it is not "_formalised_" into a "how to create personas" which is a "gap". 

@Cleop please take the _lead_ on this. Your creative skills and [iPad Pro](https://github.com/dwyl/hq/issues/435) are _perfect_ match for creating Persona Cards illustrations. 

The "MVP" of this is "_enough_" personas for CS: https://github.com/club-soda/club-soda-guide/issues/93
But we would like to develop a _tool_ for _generating_ "persona cards" in the future.
Which could be a 20% time project or even a _product_ in it's own right. 
_Every_ project we have worked on _should_ have had clearly defined persona cards _up-front_. 🥇 
Only a _handful_ of (_past_) projects have them ... 😞 
***ALL*** _future_ projects will have them. 💎 

## Todo

+ [x] `#Meta`: Craft a **`how-to-create-personas.md`** (_initial **guide**_) to **_creating_ Persona Cards** using the CS Personas as the _examples_. 
(_don't worry too much about a "general" audience understanding the CS personas, 
we will **`update`** the examples for the @dwyl app in the near future, but for now, we need to get this **done** in the context of the client project, which thankfully, is Open Source!_) 

+ [x] Create a Person Card for each of the "users" of the CS app: https://github.com/club-soda/club-soda-guide/issues/93
  > Note: _initially_ we only need **one** Persona for consumers; we can create more as required.
  + [x] Sketch a simple avatar/character for each Persona. e.g:
![image](https://user-images.githubusercontent.com/194400/45924840-acd03980-bf01-11e8-976c-4a6770c7798c.png)

+ [x] Prepare a JPEG of each Persona that we can _print_ and have on our respective wall.
  > Note: We will use the JPEG/PNG of the persona in the Digital Documentation, but having a physical print is an **_incredibly_ useful visual reminder** for Product Owner, UX Designer/Tester and Developers to refer to when writing user stories, 
  + [x] Assemble the JPEGs into a PDF for distribution and printing.

@iteles please add to this list as required. thanks.

**Comment by nelsonic** [comment]
@Cleop / @iteles I'm beginning to think that this could/should be a _dedicated_ repo:
e.g: "/**learn-how-to-create-user-personas**" (_or whatever you prefer!_)
***so that*** it's not "_hidden_" within a "process..." (_which few people will bother to read_)
I consider this a pretty core/fundamental skill/step in a developer's _personal_ learning
because developing _empathy_ for the _end-user_ is _essential_ to the success of _all_ projects,
and is something that is _relevant_ to the _entire_ community 
(_not just people following @dwyl's "processes"..._) 

Thoughts?

**Comment by Cleop** [comment]
@nelsonic - I've updated the images above to now be ordered in the same way.

**Comment by nelsonic** [comment]
@Cleop this file https://github.com/dwyl/process-handbook/blob/master/how-to-create-personas.md is a _good_ start. 👍 
I still feel that "burying" this guide in "process-handbook" is list hanging a Monet in your closet.
_Nobody_ will _see_ it here! Please consider moving it to it's own repository so that people can _discover_ it, or at _least_ linking to it from https://github.com/dwyl/learn-user-experience-testing ...
![image](https://user-images.githubusercontent.com/194400/53046119-37a06a80-3487-11e9-963e-56d5671fdf60.png)

Did you create a _template_ that people can easily follow?
and a few sample images of personas people can _use_ for their own projects?
Both of these things would be _really_ good to add to the end of the guide.
Thanks! ✨

**Comment by nelsonic** [comment]
PR #153 contains the _Template_ to create new personas. :shipit: 
Already in _use_ in https://github.com/dwyl/app/issues/213#issuecomment-650531694 ✅ 

![mia-manyinterests](https://user-images.githubusercontent.com/194400/85927108-dd45c400-b89b-11ea-80b4-b7df93925ecf.png)
