### ISSUE TITLE
Admin checklist / responsbilities

### ISSUE THREAD

**Issue by iteles** [dwyl/process-handbook#4]
You either have a founder who looks after the admin, a scrum master who does it, or a dev in the team who does it.

Either way, you need someone to make sure they have:
- [x] Total understanding of the product
- [x] Full knowledge of the product backlog
- [x] Knows how to speak to the client and can be on hand to answer questions throughout the sprint (enter examples of typical questions)
- [x] Is available to give of their product knowledge for sprint planning and estimating sessions
- [x] Agrees sprint scope
- [x] Books sprint reviews and client demos
- [ ] Invoices clients & chases those invoices

This doesn't include the more general project work like sales and contracting and making sure contracts are in place, etc.

**Comment by Cleop** [comment]
@iteles I think this list is really useful and relevant but not currently in an md file. Is this because you've not had the time or because you're unsure who this list/responsibilities should belong to?

In my eyes, this list seems spot on for 'Scrum Master Responsibilities', with the only exception of invoicing.

**Comment by iteles** [comment]
@Cleop Mostly because I didn't have time but also because I wanted to let it marinade for a little bit.

The only thing I would change above is 'Understanding of the _problem_ being solved' (and the invoicing as you say).

**Comment by Cleop** [comment]
Relates #28  I think I created #28 based off this issue. So I will collate them together.
